import React, { useEffect, useState } from "react";
import {
  Box,
  Modal,
  useToast,
  ToastDescription,
  ToastTitle,
  VStack,
  Icon,
  Center,
  Spinner,
  HStack,
  FormControl,
  Input,
  Button,
  Heading,
  Radio,
  Checkbox,
  Textarea,
  Select,
  Toast,
  ChevronDownIcon,
  CheckCircleIcon,
  CloseIcon,
  CheckIcon,
  CircleIcon,
  FormControlLabelText,
  FormControlLabel,
  InputField,
  TextareaInput,
  SelectTrigger,
  SelectDragIndicatorWrapper,
  SelectDragIndicator,
  SelectBackdrop,
  SelectIcon,
  SelectInput,
  SelectContent,
  SelectPortal,
  CheckboxGroup,
  CheckboxIndicator,
  CheckboxLabel,
  CheckboxIcon,
  ButtonText,
  ModalBody,
  ModalCloseButton,
  ModalHeader,
  ModalBackdrop,
  ModalContent,
  RadioIndicator,
  RadioLabel,
  RadioIcon,
  RadioGroup,
} from "@gluestack-ui/themed";

const PlanModal = ({ modalVisible, setModalVisible }) => {
    const [modalFormStep, setModalFormStep] = React.useState(0);
  
    
  };

  export default PlanModal;